### ISSUE TITLE
UUID is not available

### ISSUE THREAD

**Issue by narumincho** [erfanium/atlas_sdk#20] opened 2022-11-05 23:43 UTC
```ts
import { MongoClient, UUID } from "https://deno.land/x/atlas_sdk@v1.0.3/mod.ts";

const client = new MongoClient({
  endpoint: "https://data.mongodb-api.com/app/YOUR_APP_ID/endpoint/data/v1",
  dataSource: "YOUR_CLUSTER_NAME",
  auth: {
    apiKey: "YOUR_API_KEY",
  },
});

await client.database("sampleDatabase").collection("sampleCollection").insertOne({
  sampleUUID: new UUID(),
})
```

Error when trying to create document with uuid

```
error: Uncaught BSONTypeError: Unrecognized or invalid _bsontype: UUID
        throw new BSONTypeError(
              ^
    at serializeDocument (https://deno.land/x/web_bson@v0.2.5/src/extended_json.ts:318:15)
    at serializeValue (https://deno.land/x/web_bson@v0.2.5/src/extended_json.ts:253:12)
    at serializeDocument (https://deno.land/x/web_bson@v0.2.5/src/extended_json.ts:300:22)
    at serializeValue (https://deno.land/x/web_bson@v0.2.5/src/extended_json.ts:253:12)
    at serializeDocument (https://deno.land/x/web_bson@v0.2.5/src/extended_json.ts:300:22)
    at serializeValue (https://deno.land/x/web_bson@v0.2.5/src/extended_json.ts:253:12)
    at Module.stringify (https://deno.land/x/web_bson@v0.2.5/src/extended_json.ts:469:15)
    at Collection.callApi (https://deno.land/x/atlas_sdk@v1.0.3/client.ts:216:19)
    at Collection.insertOne (https://deno.land/x/atlas_sdk@v1.0.3/client.ts:81:17)
```

**Comment by erfanium** [comment] 2022-11-06 15:49
Seems a x/web_bson bug. I'll work on it

cc @lucsoft

**Comment by lucsoft** [comment] 2022-11-06 15:58
It's not a bug actually I think

We just are not up to date anymore and we need to pull from upstream

As I'm pretty sure they change upstream how they handle uuids

**Comment by erfanium** [comment] 2023-02-01 21:13
@narumincho
It's now fixed on newer atlas_sdk version.
Thanks for reporting this

**Closed as completed by erfanium** 2023-02-01 21:13 UTC
